### ISSUE TITLE
Please hide test file from users

### ISSUE THREAD

**Issue by tarsius** [10sr/with-venv-el#11]
Would you mind either renaming `tests/with-venv.el` to `tests/with-venv-tests.el` or else adding the file `tests/.nosearch`? This would ensure that a `(require 'with-venv)` does not end up trying to load `tests/with-venv.el`, which could happen if the (non-`package.el`) code responsible for adding packages to the `load-path` uses `normal-top-level-add-subdirs-to-load-path`. Likewise the tools I use to maintain the Emacsmirror would not end up preferring the test file over the library. Thanks!

**Comment by 10sr** [comment]
Sorry to be late to check this issue. I committed `.nosearch` file!

**Comment by tarsius** [comment]
Thanks!
